In [1]:
import pandas as pd

## Pandas

### Data Import
- read_csv
- iloc[]: only read the rows
- iloc[row, column]: locate to a specfic row and column
- df[column_name]: select a single column based on column name
- df[[name1,name2,...]]: the inner bracket serves as list. select multiple columns
- df[df["name1"] == "condition"]: filter the dataframe based on the column

In [ ]:
df = pd.read_csv('快递订单数据.csv')
df

   订单ID  城市  包裹数量  重量(kg)  发货时间(小时)
0  A001  北京   3.0     2.5      24.0
1  A002  广州   NaN     1.0      36.0
2  A003  深圳   5.0     3.3       NaN
3  A004  北京   3.0     2.0      30.0
4  A005  上海   4.0     2.8      48.0

In [ ]:
df.iloc[1:3,[0,3]] #filter by index to

In [13]:
df[(df['城市'] == '上海') & (df['重量(kg)'] > 2)]

   订单ID  城市  包裹数量  重量(kg)  发货时间(小时)
4  A005  上海   4.0     2.8      48.0
6  A007  上海   4.0     2.4      42.0

### Group by & Agg (for multiple metrics)

In [14]:
df.groupby('城市')['重量(kg)'].mean()

城市
上海    2.600000
北京    2.250000
广州    1.533333
深圳    3.300000
Name: 重量(kg), dtype: float64

In [17]:
df.groupby('城市')['重量(kg)'].agg(['mean','max','min']).rename(columns={'mean':'平均重量','max':'最大重量','min':'最小重量'})

        平均重量  最大重量  最小重量
城市
上海  2.600000   2.8   2.4
北京  2.250000   2.5   2.0
广州  1.533333   1.9   1.0
深圳  3.300000   3.3   3.3

### Merge and Join
- merge: df.merge(df2, on = 'column', how = 'left/right')
- join: you must set the index

In [23]:
city_df = pd.read_csv('city_df.csv')
city_df.columns

Index(['城市', '区域'], dtype='object')

In [33]:
df_merged = df.merge(city_df, on='城市', how='left')

In [37]:
df_merged = df_merged.dropna().drop_duplicates()

In [38]:
df_merged

   订单ID  城市  包裹数量  重量(kg)  发货时间(小时)  区域
0  A001  北京   3.0     2.5      24.0  华北
3  A004  北京   3.0     2.0      30.0  华北
4  A005  上海   4.0     2.8      48.0  华东
5  A006  广州   2.0     1.9      36.0  华南
6  A007  上海   4.0     2.4      42.0  华东
7  A008  北京   3.0     2.5      24.0  华北
8  A009  广州   2.0     1.7      36.0  华南

In [47]:
# df.set_index('城市',inplace = True)
# city_df.set_index('城市',inplace = True)
df_joined = df.join(city_df)
df_joined.reset_index()

     城市  订单ID  包裹数量  重量(kg)  发货时间(小时)   区域
0    北京  A001   3.0     2.5      24.0   华北
1    广州  A002   NaN     1.0      36.0   华南
2    深圳  A003   5.0     3.3       NaN  NaN
3    北京  A004   3.0     2.0      30.0   华北
4    上海  A005   4.0     2.8      48.0   华东
5    广州  A006   2.0     1.9      36.0   华南
6    上海  A007   4.0     2.4      42.0   华东
7    北京  A008   3.0     2.5      24.0   华北
8    广州  A009   2.0     1.7      36.0   华南
9   NaN  A010   5.0     NaN      60.0  NaN
10   北京  A004   3.0     2.0      30.0   华北

## Numpy

In [48]:
import numpy as np

In [ ]:
s